name: MacOS SDL2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: |
          set -e
          brew unlink python3
          brew upgrade && brew install --overwrite python3
          brew install cmake make imagemagick
          pip3 install cogapp generate-iconset
          brew install mingw-w64 openal-soft sdl2 sdl2_mixer glew libmodplug libpng
          brew install openssl@1.1 protobuf
    - name: cmake
      run: export HOMEBREW_PREFIX="/usr/local" && chmod +x ./.github/build_macos.sh && ./.github/build_macos.sh
