name: Ubuntu 20.04 SDL2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential cmake make python3 python3-pip bison imagemagick libgtk-3-dev
          sudo pip3 install cogapp
          sudo apt-get install -y zsh mingw-w64 clang libsdl2-dev libsdl2-mixer-dev libopenal-dev libglew-dev libssl-dev libprotobuf-dev protobuf-compiler libpng-dev libcurl4-openssl-dev
    - name: cmake
      run: export CC=clang && export CXX=clang++ && ./build_linux64.sh
