name: Ubuntu 22.04 SDL2

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-22.04

    env:
      OPENJKDF2_BUILD_DIR: /tmp/OpenJKDF2/Linux/x86_64/Debug
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
        name: Checkout
      - name: Install Packages
        run: |
          sudo apt-get update -qq &&
          sudo apt-get install -y build-essential cmake make clang python3 python3-pip bison imagemagick zsh \
                                  libgtk-3-dev libsdl2-dev libsdl2-mixer-dev libopenal-dev libglew-dev libssl-dev libprotobuf-dev libpng-dev libcurl4-openssl-dev \
                                  protobuf-compiler &&
          sudo pip3 install cogapp
      - name: Generate CMake Build System
        run: cmake -DCMAKE_BUILD_TYPE=Debug -B "$OPENJKDF2_BUILD_DIR"
      - name: Make
        run: make -C "$OPENJKDF2_BUILD_DIR"
